### ISSUE TITLE
shapFlex::r2 returned NaN for r2_shap

### ISSUE THREAD

**Issue by paullevchuk** [nredell/shapFlex#13]
I used your cool function and it worked well, but for one dataset it returned me NaN.
![image](https://user-images.githubusercontent.com/13118064/94412189-2b5fb180-0182-11eb-8d0e-4ff6b995945d.png)

**Comment by nredell** [comment]
Well that's no good. If you send a reproducible example we may be able to fix it.

**Comment by paullevchuk** [comment]
I'm sorry for disturbing you. I reran my h2o R-code and after that your function worked well.

**Comment by nredell** [comment]
Right on. No problem at all. Glad it's working.
